backend:
  name: git-gateway
  branch: main # Change to 'master' if your default branch is master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "songs"
    label: "Songs"
    folder: "content/songs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Lyrics", name: "lyrics", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
